import "server-only";

import { RunnableToolFunction } from "openai/lib/RunnableFunction";
import { isDeskNetsAgentEnabled, runDeskNetsAgent } from "./desknets-agent-client";
import type { DeskNetsAgentRunResponse } from "./desknets-agent-types";

type DeskNetsToolArguments = Record<string, never>;

function formatToolResult(run: DeskNetsAgentRunResponse) {
  const message =
    run.result?.assistantMessage?.trim() ||
    run.message?.trim() ||
    run.error?.trim() ||
    run.result?.summary?.trim() ||
    "DeskNet's Agentの処理が完了しました。";

  return {
    status: run.status,
    runId: run.id || run.runId,
    message,
  };
}

export function createDeskNetsAgentTool(
  chatThreadId: string,
  userPrompt: string
): RunnableToolFunction<DeskNetsToolArguments> {
  return {
    type: "function",
    function: {
      name: "desknets_schedule_agent",
      description:
        "DeskNet'sのスケジュールを確認し、参加者・日時条件に基づいて予定追加画面まで操作する。最終登録ボタンは実行しない。DeskNet'sの予定調整を依頼された場合のみ使用する。",
      parameters: {
        type: "object",
        properties: {},
        additionalProperties: false,
      },
      parse: JSON.parse,
      function: async (_args: DeskNetsToolArguments) => {
        if (!isDeskNetsAgentEnabled()) {
          return {
            status: "disabled",
            message: "DeskNet's Agent is not enabled in this environment.",
          };
        }

        // Tool arguments are generated by the LLM and may paraphrase or duplicate
        // participants. Always send the exact latest user message to the Agent API.
        const run = await runDeskNetsAgent(userPrompt, chatThreadId);
        // Do not expose or persist the full browser run, screenshots, participant
        // identifiers, or facility inventory in the normal chat transcript.
        return formatToolResult(run);
      },
    },
  };
}
